# Generated by Django 5.2.3 on 2025-06-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_order_used_reward_coupon_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
