# Generated by Django 5.2.3 on 2025-06-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ordersummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_summary',
        ),
    ]
